### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by WeiWangHUST** [topasmc/dicom-interface#8]
Dear experts:
      I have installed the extension using RTplan dicom interface with Topas.
      I have a RTplan dicom file now,please tell me how to do a plan simulation.
      should i creat a treatment mechine?
      Thanks!

**Comment by jungwookshin** [comment]
Thank you for your interests in this project. Hope you are questioning about pencil beam scanning simulations because DICOM-RT Ion plan/record are the ones we support right now. 

Yes, basicailly you need to create your treatment machine. There are two ways to create a treatment machine (TM), C++ or through machine description file. For your example, I have created an example plan and explained that wiki (https://github.com/topasmc/dicom-interface/wiki/direct-implementation). So you can follow the steps in that page. I just found that the code for machine-description file is in my private branch. Until this will be merged with other developments, please consider to implement your TM with C++. 

I can help you to implement your own TM but you should know physical characteristics for your spot, which are not part of your DICOM-RT Ion Plan. For example, you need to know how to relate the nominal energy per spot in DICOM with energy spectrum (distribution) for MC simulations.

**Comment by WeiWangHUST** [comment]
Hello jungwookshin：
Thanks your help and reply !yes, i are questioning about pensil beam scanning simulation. because i am a student,so i have much problem，i hope you can help me !
What more physical characteristics of my spots not included the RTplan should we know?

**Comment by jungwookshin** [comment]
In addition to energy spectrum, distributions of spot-size and spot-divergence are important to simulate your system correctly. If you do not know all these distributions, you can start with estimated values and tune these values by benchmarking against your measurement data.

Have you followed up the tutorial about direct-implementation in this project wiki? You need to follow up the wiki first and then extend your experiences from the tutorial for your system.
